name: equip_it_public
description: A program to rent equipment and manage staff.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  http: ^0.13.4
  url_launcher: ^6.0.12
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  file_picker: ^4.3.3
  uuid: ^3.0.6
  decimal: ^2.1.0

  cupertino_icons: ^1.0.2

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/images/

  uses-material-design: true
